export type AdminScriptRiskLevel = "read-only" | "write";

export type AdminScriptCategory = "Suppliers" | "Catalog" | "Orders";

export type AdminScriptInputKind = "url";

export type AdminScriptInputDefinition = {
  id: string;
  label: string;
  placeholder: string;
  description: string;
  kind: AdminScriptInputKind;
};

export type AdminScriptDefinition = {
  id: string;
  npmScript: string;
  title: string;
  category: AdminScriptCategory;
  description: string;
  inputSummary: string;
  outputSummary: string;
  impact: string;
  expectedDuration: string;
  riskLevel: AdminScriptRiskLevel;
  dryRunByDefault: boolean;
  timeoutMs: number;
  safetyNote: string;
  inputs?: readonly AdminScriptInputDefinition[];
};

export const ADMIN_SCRIPT_DEFINITIONS: readonly AdminScriptDefinition[] = [
  {
    id: "suppliers:sync-stock",
    npmScript: "suppliers:sync-stock",
    title: "Sync supplier stock",
    category: "Suppliers",
    description:
      "Pull the latest supplier availability and update local inventory quantities for tracked products.",
    inputSummary:
      "Uses the supplier mappings and tracked catalog products already configured in Smokeify. No manual link input is required.",
    outputSummary:
      "Updates local inventory quantities and stock availability for mapped supplier products.",
    impact: "Writes inventory and stock availability data.",
    expectedDuration: "2-10 minutes",
    riskLevel: "write",
    dryRunByDefault: false,
    timeoutMs: 10 * 60 * 1000,
    safetyNote: "Run deliberately. This updates sellable stock data immediately.",
  },
  {
    id: "bloomtech:scrape-category-preview",
    npmScript: "bloomtech:scrape-category-preview",
    title: "Bloomtech category scrape preview",
    category: "Suppliers",
    description:
      "Scrape a Bloomtech category or brand listing page and build a preview payload from the products linked on that page.",
    inputSummary:
      "Optional Bloomtech category or brand listing URL. Leave it empty to use the default Bloomtech source category.",
    outputSummary:
      "Writes a preview JSON file at scripts/bloomtech/supplier-preview.json for review or later import.",
    impact: "Refreshes preview files only.",
    expectedDuration: "1-5 minutes",
    riskLevel: "read-only",
    dryRunByDefault: true,
    timeoutMs: 8 * 60 * 1000,
    safetyNote: "Use this only for listing pages. It rejects direct product URLs.",
    inputs: [
      {
        id: "sourceUrl",
        label: "Bloomtech category link",
        placeholder: "https://bloomtech.de/Biobizz_1",
        description:
          "Paste a Bloomtech category, brand, or listing URL. Do not use a single product URL here.",
        kind: "url",
      },
    ],
  },
  {
    id: "bloomtech:scrape-product-preview",
    npmScript: "bloomtech:scrape-product-preview",
    title: "Bloomtech product scrape preview",
    category: "Suppliers",
    description:
      "Scrape a single Bloomtech product page and build a one-item preview payload without scanning a category listing.",
    inputSummary:
      "Bloomtech product URL only. Leave it empty only if you want the script's default URL instead of a custom product page.",
    outputSummary:
      "Writes a preview JSON file at scripts/bloomtech/supplier-preview.json containing the single scraped product.",
    impact: "Refreshes preview files only.",
    expectedDuration: "30-90 seconds",
    riskLevel: "read-only",
    dryRunByDefault: true,
    timeoutMs: 5 * 60 * 1000,
    safetyNote: "Use this only for direct product pages. It rejects category and listing URLs.",
    inputs: [
      {
        id: "sourceUrl",
        label: "Bloomtech product link",
        placeholder: "https://bloomtech.de/BioBizz-Bio-Grow-250-ml",
        description:
          "Paste one direct Bloomtech product URL. Use the category scraper for listing pages.",
        kind: "url",
      },
    ],
  },
  {
    id: "bloomtech:import-preview",
    npmScript: "bloomtech:import-preview",
    title: "Bloomtech import preview",
    category: "Suppliers",
    description:
      "Read the prepared Bloomtech preview file and prepare product create or update actions for Bloomtech-linked catalog records.",
    inputSummary:
      "Consumes scripts/bloomtech/supplier-preview.json generated by the Bloomtech scraper preview.",
    outputSummary:
      "Returns an import summary in stdout and, when the underlying script is run in apply mode, creates or updates Bloomtech-linked catalog records.",
    impact: "Prepares or writes supplier-linked catalog records, depending on script mode.",
    expectedDuration: "2-8 minutes",
    riskLevel: "write",
    dryRunByDefault: false,
    timeoutMs: 10 * 60 * 1000,
    safetyNote: "Use only after validating the preview file. This changes live catalog data.",
  },
  {
    id: "bloomtech:report-missing-costs",
    npmScript: "bloomtech:report-missing-costs",
    title: "Bloomtech missing costs report",
    category: "Suppliers",
    description:
      "Report Bloomtech variants that still have missing or invalid cost data.",
    inputSummary:
      "Reads existing Bloomtech-linked catalog records and variant pricing data from the database.",
    outputSummary:
      "Produces a diagnostic missing-cost report in stdout without modifying catalog data.",
    impact: "Produces a diagnostic report only.",
    expectedDuration: "30-90 seconds",
    riskLevel: "read-only",
    dryRunByDefault: true,
    timeoutMs: 3 * 60 * 1000,
    safetyNote: "Use before pricing overrides to catch incomplete supplier cost coverage.",
  },
  {
    id: "b2b-headshop:scrape-preview",
    npmScript: "b2b-headshop:scrape-preview",
    title: "B2B Headshop scrape preview",
    category: "Suppliers",
    description:
      "Fetch the latest B2B Headshop supplier catalog into the local preview JSON without importing it.",
    inputSummary:
      "Uses the script's configured B2B Headshop source page and optional supplier authentication from environment variables.",
    outputSummary:
      "Writes a preview JSON file at scripts/b2b-headshop/supplier-preview.json for inspection.",
    impact: "Refreshes preview files only.",
    expectedDuration: "1-5 minutes",
    riskLevel: "read-only",
    dryRunByDefault: true,
    timeoutMs: 8 * 60 * 1000,
    safetyNote: "Safe for inspection. Use this before any B2B Headshop override run.",
  },
  {
    id: "b2b-headshop:report-missing-costs",
    npmScript: "b2b-headshop:report-missing-costs",
    title: "B2B Headshop missing costs report",
    category: "Suppliers",
    description:
      "Report B2B Headshop variants that still have missing or invalid cost data.",
    inputSummary:
      "Reads existing B2B Headshop-linked catalog records and variant pricing data from the database.",
    outputSummary:
      "Produces a diagnostic missing-cost report in stdout without modifying catalog data.",
    impact: "Produces a diagnostic report only.",
    expectedDuration: "30-90 seconds",
    riskLevel: "read-only",
    dryRunByDefault: true,
    timeoutMs: 3 * 60 * 1000,
    safetyNote: "Use before pricing overrides to catch incomplete cost data.",
  },
  {
    id: "catalog:update-bestseller-scores",
    npmScript: "catalog:update-bestseller-scores",
    title: "Update bestseller scores",
    category: "Catalog",
    description:
      "Recompute bestseller scoring used by catalog merchandising and ranking surfaces.",
    inputSummary:
      "Reads existing catalog product performance and ranking signals already stored by Smokeify.",
    outputSummary:
      "Updates derived bestseller score fields used by merchandising and ranking surfaces.",
    impact: "Writes derived catalog ranking fields.",
    expectedDuration: "30-120 seconds",
    riskLevel: "write",
    dryRunByDefault: false,
    timeoutMs: 4 * 60 * 1000,
    safetyNote: "Safe when merchandising data needs a refresh. No checkout data is changed.",
  },
  {
    id: "orders:backfill-payment-fees",
    npmScript: "orders:backfill-payment-fees",
    title: "Backfill payment fees",
    category: "Orders",
    description:
      "Backfill Stripe payment fee data for historical orders that are missing reconciliation details.",
    inputSummary:
      "Reads historical order and Stripe reconciliation data for orders that still have missing payment fees.",
    outputSummary:
      "Writes missing historical payment fee values back to affected order records.",
    impact: "Writes historical order finance fields.",
    expectedDuration: "1-6 minutes",
    riskLevel: "write",
    dryRunByDefault: false,
    timeoutMs: 8 * 60 * 1000,
    safetyNote: "Run when finance data is incomplete. This updates historical order records.",
  },
] as const;

export function getAdminScriptDefinition(scriptId: string) {
  return ADMIN_SCRIPT_DEFINITIONS.find((definition) => definition.id === scriptId) ?? null;
}
