ALTER TABLE "Order"
ADD COLUMN "paymentMethod" TEXT;

ALTER TABLE "OrderItem"
ADD COLUMN "baseCostAmount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "paymentFeeAmount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "adjustedCostAmount" INTEGER NOT NULL DEFAULT 0;
