import { notFound } from "next/navigation";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import AdminThemeToggle from "@/components/admin/AdminThemeToggle";

export default async function AdminInventoryAdjustmentsPage() {
  const session = await getServerSession(authOptions);
  const isAdmin = session?.user?.role === "ADMIN";
  if (!isAdmin) notFound();

  const adjustments = await prisma.inventoryAdjustment.findMany({
    orderBy: { createdAt: "desc" },
    take: 200,
    include: {
      product: { select: { title: true, manufacturer: true } },
      variant: { select: { title: true } },
      order: { select: { orderNumber: true } },
    },
  });

  return (
    <div className="admin-legacy-page space-y-6">
      <section className="overflow-hidden rounded-[32px] border border-white/10 bg-[linear-gradient(135deg,rgba(18,22,29,0.98),rgba(8,12,18,0.98))] p-6 shadow-[0_30px_80px_rgba(0,0,0,0.35)]">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <p className="text-[11px] font-semibold uppercase tracking-[0.35em] text-slate-500">
              Admin / Inventory
            </p>
            <h1 className="mt-3 text-3xl font-semibold text-white">
              Inventory adjustments
            </h1>
            <p className="mt-3 max-w-2xl text-sm text-slate-400">
              Recent stock deltas generated by live checkout and order flows.
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <AdminThemeToggle />
            <div className="inline-flex items-center rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-xs font-semibold text-slate-300">
              Latest 200 adjustments
            </div>
          </div>
        </div>
      </section>

      {adjustments.length === 0 ? (
        <div className="rounded-[28px] border border-white/10 bg-white/[0.03] p-6 text-sm text-slate-500">
          No inventory adjustments yet.
        </div>
      ) : (
        <div className="overflow-hidden rounded-[28px] border border-white/10 bg-[#090d12] shadow-[0_18px_50px_rgba(0,0,0,0.22)]">
          <div className="grid grid-cols-1 gap-3 border-b border-white/10 bg-white/[0.03] px-4 py-3 text-[11px] font-semibold uppercase tracking-[0.24em] text-slate-500 sm:grid-cols-[1.5fr_1fr_0.6fr_0.8fr_1.2fr]">
            <div>Item</div>
            <div>Order</div>
            <div>Delta</div>
            <div>Reason</div>
            <div>Time</div>
          </div>
          <div className="divide-y divide-white/5">
            {adjustments.map((entry) => {
              const productName = entry.product.manufacturer
                ? `${entry.product.manufacturer} ${entry.product.title}`
                : entry.product.title;
              const variantTitle = entry.variant.title;
              return (
                <div
                  key={entry.id}
                  className="grid grid-cols-1 gap-3 px-4 py-3 text-sm text-slate-300 sm:grid-cols-[1.5fr_1fr_0.6fr_0.8fr_1.2fr]"
                >
                  <div>
                    <div className="font-semibold text-slate-100">{productName}</div>
                    {variantTitle ? (
                      <div className="text-xs text-slate-500">{variantTitle}</div>
                    ) : null}
                  </div>
                  <div className="text-xs text-slate-400">
                    {entry.order?.orderNumber ? `#${entry.order.orderNumber}` : "—"}
                  </div>
                  <div className="text-xs font-semibold text-amber-300">
                    {entry.quantityDelta}
                  </div>
                  <div className="text-xs text-cyan-300">{entry.reason}</div>
                  <div className="text-xs text-slate-500">
                    {new Date(entry.createdAt).toLocaleString("de-DE")}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
